# Site settings
title: Thoughts on Practical Quantum Chemistry
email: dbwy@u.washington.edu
description: > # this means to ignore newlines until "baseurl:"
  An accessable view on various topics in the practical implementation
  of approximate quantum mechanical methods and their application to
  molecular systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wavefunction91
github_username:  wavefunction91

# Build settings
markdown: kramdown
